# Generated by Django 4.2.3 on 2023-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_alter_cartitem_id_alter_order_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='deleted_at',
            field=models.DateField(null=True),
        ),
    ]
