# Generated by Django 4.2.3 on 2023-07-12 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homePage', '0003_alter_productcategory_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='user_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
